name: test

on:
  push:
    branches:
      - main
  #   paths:
  #   - 'environments/prod/values.prod.yaml'
  #   - 'environments/prod/saas-app-prod/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # env:
    #   MAGDA_FQDN: prod-stable
    #   CLUSTER_ZONE: australia-southeast1

    name: Test job
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Run JS
        id: runJs
        run: node index.js
        env:
          CHANGED_FILES: "${{ steps.files.outputs }}"
