name: publish-map-config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-map-config:
    runs-on: ubuntu-latest
    # env:
    #   MAGDA_FQDN: prod-stable
    #   CLUSTER_ZONE: australia-southeast1

    name: Publish map-config
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Run JS
        id: runJs
        run: node index.js
        env:
          DEV_MAGDA_FQDN: ${{ secrets.DEV_MAGDA_FQDN }}
          DEV_MAGDA_API_ID: ${{ secrets.DEV_MAGDA_API_ID }}
          DEV_MAGDA_API_KEY: ${{ secrets.DEV_MAGDA_API_KEY }}
          ADDED_FILES: "${{ steps.files.outputs.added }}"
          MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
          # REMOVED_FILES: "${{ steps.files.outputs.removed }}"
          # RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
