name: dev-dif-map-config

on:
  pull_request:
    branches:
      - main

jobs:
  dev-dif-map-config:
    runs-on: ubuntu-latest

    name: DEV dif map-config
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Show changed files
        id: runJs
        run: node index.js
        env:
          # This is used to find map-config files from `map-configs.json`
          ENVIRONMENT_TAG: "dev"
          SKIP_PUSH: true
          ADDED_FILES: "${{ steps.files.outputs.added }}"
          MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
          # These are not used at the moment
          # REMOVED_FILES: "${{ steps.files.outputs.removed }}"
          # RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
